// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbMxRhk9l3FdbLLz8TMuAryvtINUkFEY8',
    appId: '1:992693178478:web:6187e1a573d393ba7e167f',
    messagingSenderId: '992693178478',
    projectId: 'auth-demo-98847',
    authDomain: 'auth-demo-98847.firebaseapp.com',
    databaseURL: 'https://auth-demo-98847-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'auth-demo-98847.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX_CS8hezJp1ENqxHax9yXXxefkDLpe4M',
    appId: '1:992693178478:android:8af077322fc4190b7e167f',
    messagingSenderId: '992693178478',
    projectId: 'auth-demo-98847',
    databaseURL: 'https://auth-demo-98847-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'auth-demo-98847.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5AZpLhQe-g_0q5kGXKfODneWK-D3LJEE',
    appId: '1:992693178478:ios:528f6e0ae458b0da7e167f',
    messagingSenderId: '992693178478',
    projectId: 'auth-demo-98847',
    databaseURL: 'https://auth-demo-98847-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'auth-demo-98847.appspot.com',
    iosBundleId: 'com.example.moneyWather',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5AZpLhQe-g_0q5kGXKfODneWK-D3LJEE',
    appId: '1:992693178478:ios:e9ad95b0b43db3b87e167f',
    messagingSenderId: '992693178478',
    projectId: 'auth-demo-98847',
    databaseURL: 'https://auth-demo-98847-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'auth-demo-98847.appspot.com',
    iosBundleId: 'com.example.moneyWather.RunnerTests',
  );
}
